<a href="https://colab.research.google.com/github/singammanasvi9440/Assignment-3/blob/main/Machine_Learning_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Numpy




In [1]:
# a.Create a random vector of size 15 having Integers in the range of 1-20.
import numpy as np
v =  np.random.randint(1,20,(15,))

# Reshape the array into 3 x 5 
arr = v.reshape(3,5)
print(arr.shape)
print(arr)

# Replace the max in each row by 0
row_max = arr.max(axis=1).reshape(-1,1)
arr = np.where(arr == row_max, 0, arr)
print('\n',arr)

(3, 5)
[[11  2  6  4  6]
 [10 18 14  5  1]
 [ 9 13  5  8 15]]

 [[ 0  2  6  4  6]
 [10  0 14  5  1]
 [ 9 13  5  8  0]]


In [2]:
# Create a 2-d array of size 4 x 3 (composed of 4-byte integer elements),print the shape, type and data type of the array
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 5, 7]], np.int32)
print('Shape:', x.shape)
print('Type:', type(x))
print('Data type:', x.dtype)

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [3]:
#b. Compute the eigenvalues and right eigenvectors
from numpy import linalg as LA
mat = np.array([[3, -2], [1, 0]], np.int32)
w, v = LA.eig(mat)
print('Eigenvalues:', w)
print('\nRight eigenvectors:\n', v)

Eigenvalues: [2. 1.]

Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
#c. Compute the sum of the diagonal elements with trace
n = np.array([[0, 1, 2], [3, 4, 5]])
res = np.trace(n)
print('Sum of diagonal elements:', res)

Sum of diagonal elements: 4


In [5]:
#d.
m = np.arange(1,7).reshape(3,2)
m = m.reshape(2,3)


### 2. Matplotlib

In [6]:
import matplotlib.pyplot as plt
languages = ['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++']
popularity = np.array([22.2, 17.6, 8.8, 8, 7.7, 6.7])
exp = [0.2, 0, 0, 0, 0, 0]
plt.pie(popularity, labels = languages, explode = exp, shadow = True, autopct='%1.1f%%', startangle = 135)
plt.show()